#!/usr/bin/env php
<?php

declare(strict_types=1);

use Laravel\Lumen\Application;
use Noffily\Teapot\Core\Runner;
use Noffily\Teapot\Core\Emitter;
use Illuminate\Http\Request;
use Nyholm\Psr7\Factory\Psr17Factory;
use Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory;

require 'vendor/autoload.php';

$app = new Application();

$app->router->get('/', function() {
    return '<a href="/hello/world">Try /hello/world</a>';
});

$app->router->get('/hello/{name}', function ($name) {
    return "Hello, $name";
});

$psr17Factory = new Psr17Factory();
$psrHttpFactory = new PsrHttpFactory($psr17Factory, $psr17Factory, $psr17Factory, $psr17Factory);

$emitter = new Emitter(Closure::fromCallable(function ($request) use ($app, $psrHttpFactory) {
    return $psrHttpFactory->createResponse($app->handle($request));
}));

class TestCase {
    public function testHomePage(Runner $runner)
    {
        $request = Request::create('/');
        $result = $runner->execute($request);

        $result->seeResponseCodeIs(200);
        $result->seeResponseBodyContentsIs('<a href="/hello/world">Try /hello/world</a>');
    }

    public function testHello(Runner $runner)
    {
        $request = Request::create('/hello/noffily');
        $result = $runner->execute($request);

        $result->seeResponseCodeIs(200);
        $result->seeResponseBodyContentsIs('Hello, noffily');
    }
}

$testCase = new TestCase();
$testCase->testHello(new Runner($emitter));
$testCase->testHomePage(new Runner($emitter));

echo 'done';

